library(lubridate)
png(filename = "plot1.png",width = 480, height = 480)
dat<-read.table("household_power_consumption.txt",sep=";",header=TRUE,stringsAsFactors=FALSE,na.strings="?")
dat$Date<-as.Date(dat$Date, "%d/%m/%Y")
subdat<-subset(dat,dat$Date > as.Date("2007-01-31") & dat$Date < as.Date("2007-02-03"))
subdat$Time<-ymd_hms(paste(subdat$Date, subdat$Time))
par(cex=0.75)
hist(subdat$Global_active_power,col="red",main="Global Active Power",xlab="Global Active Power (kilowatts)")
dev.off()
